name: Deploy to Github packages
on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy to Github Packages
      #run: mvn -B deploy -s settings.xml -Dgithub.user=boxi79 -Dgithub.password=${{ secrets.BSR_TOKEN }}
      run: mvn -B deploy -s settings.xml -Dgithub.user=boxi79 -Dgithub.password=${{ secrets.BSR_TOKEN }} --file pom.xml
